### ISSUE TITLE
時刻が重なる場合の挙動

### ISSUE THREAD

**Issue by 8245snake** [8245snake/MyWorks#22]
開始/終了時刻を編集したときに他の予定と時刻が重なるときの挙動を定義したい。

**Comment by jellyfish8245** [comment]
編集がしづらくなる仕様は避けたい。（一時的な重なりを許容してもらえた方がいいかなぁ）
でも際限なく重なるのも困る。（現状だと重なっている部分が分かりづらいため、下手すると合計時間とあわなくなったことに気づけない。⇒重なりを許可しつつもアラート出すか重なっているタスクの色を強制変更するか強調表示するか等？？）
