### ISSUE TITLE
予定をタイムラインではなく単純なリストで表示するモード

### ISSUE THREAD

**Issue by 8245snake** [8245snake/MyWorks#23]
短い予定がぎっしり詰まっている場合に選択しやすいようにリストを用意する。
タイムラインとの二者択一タブ表示にすれば使い分け可能か。

**Comment by jellyfish8245** [comment]
たしかに、帯の長さに関わらず、一定幅（高さ）のリストで上から順に並んでくれたら価値ありそう。
タイムラインとの二者択一タブ表示には賛成（想定デザイン気になるところ）
