### ISSUE TITLE
タスクの中断と複製機能

### ISSUE THREAD

**Issue by 8245snake** [8245snake/MyWorks#28]
** タスクの中断

選択したタスクを半分くらいの時間で分割する（分割した片割れはどこかに保存して再開できるようにするか、後述の複製機能でスケジュールする）

中断というより割り込み機能と言う方が近いかも。ボタンを押したら現在進行かのタスクを終了して新しいタスクを入れるようなするか。

** タスクの複製

選択したタスクをコピーする。複数日にコピーできたら便利なのでクリップボード領域みたいなところに貯めておく。貼り付ける操作は編集エリアにボタンを置くか？

**Comment by jellyfish8245** [comment]
あまりまとまっていないがメモ。

**タスクの中断

　現在進行形でタスク管理や予定のタスク組みをしているときは有用にも思えるが、現在時刻という縛りが厳しい。
　結局現在時刻よりも前か後にずらしたくなってしまう場合にあまり有用でない。
　指定時間で切って次を入れるというのが１操作でできると楽に思う。
　タスクの新規追加の際に、開始時間を指定して追加できる機能もあると便利という気持ち。
（重なり許容か切って貼るかは未定。指定時刻がまるっと他タスクと被る場合に、最悪前のタスクが消えてしまう恐れがありそう。）

**タスクの複製

　タスクの複製はよい。たしかに、いちいちメンテナンスしてよく使うタスクに入れる程ではないが…というのがありそう。
　最低限タイトルと作業分類がコピーされれば…。欲言うとメモ内容も。タイトルだけだったらセルフコピペするから不要。
　ToDoの他に、作業中タスクみたいな感じでコピペのクリップボードを開閉で置いておくとかもどうだろうか？

**Comment by 8245snake** [comment]
一旦コピー機能のみ作って様子を見ることにする
