### ISSUE TITLE
クリックしたところにタスクを登録する機能

### ISSUE THREAD

**Issue by 8245snake** [8245snake/MyWorks#4]
Outlookのカレンダーみたいに入れる

**Comment by jellyfish8245** [comment]
初期展開は1時間固定、または終了時間を未定（可能？）か24時に設定、もしくは初期時間を設定出しにするのはどうか。
（ドラッグ＆ドロップで開始～終了を決める操作は不要と考える。すぐタスクの入力ができればそれでよいのでは。）
